# Site settings
title: Azimuth Design
email: theme@viennalabs.com
description: > # this means to ignore newlines until "baseurl:"
 Modern, affordable custom design solutions.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "azimuthdesign.ca" # the base hostname & protocol for your site

twitter_username: volnyio
github_username:  volny

# Build settings
markdown: kramdown
