# Site settings
title: Azimuth Designs
email:
description: Simple, sleek custom furniture design> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "azimuthdesign.ca" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
